### PR TITLE
Reggie tasks

### LINKED ISSUE #3: Add your previous work experiences
Task 3 of the portfolio site orientation project.

### LINKED ISSUE #4: Add your hobbies (including images)
Task 4 of the portfolio project orientation site.

### LINKED ISSUE #7: Add a menu bar that dynamically displays other pages in the app

### PR DESCRIPTION
**Pull request by Reggie-Amedee-Tech**
This PR is responsible for completing tasks 3 and 4. It also completes the requirement of having a navigation bar on one of our web pages. I was able create one template file and render the data dynamically using python in
the init file. I tried my best to make the hobby and experience pages web responsive!

Screenshot 2023-06-26 at 3 50 56 PM
Screenshot 2023-06-26 at 3 50 30 PM
Screenshot 2023-06-26 at 3 50 14 PM
Screenshot 2023-06-26 at 3 49 56 PM
Screenshot 2023-06-26 at 3 49 44 PM

### CODE REVIEW

**Review by casseyshao — COMMENTED** [review]
This looks good to me! I like that only the fellow data changes, and the components are reused keeping the code clean and reusable! Code looks good! This is super minor but if you want, maybe some screenshots could be added to the PR as a reference for what everything looks like! Up to you though!!

**Comment by Reggie-Amedee-Tech** [comment]
I like that idea! I never really used screen shots in my prs it I can def
see the benefit of doing so. I’ll add them shortly.

**Comment by Ebot101** [comment]
Hey Reggie, The code looks great! I would say that the only thing to add to the pr would be a sc of what the code actually looks like in the browser, but other than that, great work!

**Comment by Reggie-Amedee-Tech** [comment]
Hi Cassey,

Thank you for your valuable feedback. I added some images to my pr.

**Pull request merged**
