### PR TITLE
Add map of all locations visited by fellows

### LINKED ISSUE #6: Add a map of all the cool locations/countries you visited
Task 6 of the portfolio project orientation site.

### PR DESCRIPTION
**Pull request by casseyshao**
This PR contains changes to add a map of all the locations visited by our group to the landing page. Folium needs to be installed to the virtual environment with `pip install folium`.
Screen Shot 2023-06-27 at 10 24 20 AM
Screen Shot 2023-06-27 at 10 24 48 AM

### CODE REVIEW

**Comment by Reggie-Amedee-Tech** [comment]
I love this! 

Is there a way to visually link the fellow with the pins that are on the map? I'm assuming I am the green pin because I went to iceland, I think it would be cool if it was easy to tell which fellow went to went where, you know? 

I don't know if the map library has some sort of feature like that but I think it would be cool and convey important information.

What do you think?

**Comment by Ebot101** [comment]
Hey Cassey! The map looks great! I don't really have any critiques on the code either, nice work!

**Comment by casseyshao** [comment]
Screen Shot 2023-06-27 at 3 20 00 PM
Here is an updated legend!

**Comment by Reggie-Amedee-Tech** [comment]
This looks great!

It came out so well.

Awesome Job Cassey!

**Comment by Reggie-Amedee-Tech** [comment]
1 x1 w cassey
Friday Jun 30, 2023 ⋅ 1pm – 2pm
Eastern Time - New York

Join with Google Meet
https://meet.google.com/vjf-mwfy-yfj?hs=224




Organizer
***@***.***
***@***.***

Guests
***@***.*** - organizer
***@***.***
View all guest info  
https://calendar.google.com/calendar/event?action=VIEW&eid=NG4wbzNkMXRpYzhhc3NpMDM3Y2RxbG12cW0gcmVwbHkrYXN2ZWN2bW50eG9iMzRxeTdiY3NyaG9jdmJ1MmZldmJuaGhndDNlNnFlQHJlcGx5LmdpdGh1Yi5jb20&tok=MjcjamVhbnRlY2huaWNhbDE5OTJAZ21haWwuY29tZjY4ODA1YmNjMTg0ZDNjYjEzZDgzOTJkMjQ2OGM4M2IxOTdiZGM1MA&ctz=America%2FNew_York&hl=en&es=0

Reply for ***@***.***  
and view more details  
https://calendar.google.com/calendar/event?action=VIEW&eid=NG4wbzNkMXRpYzhhc3NpMDM3Y2RxbG12cW0gcmVwbHkrYXN2ZWN2bW50eG9iMzRxeTdiY3NyaG9jdmJ1MmZldmJuaGhndDNlNnFlQHJlcGx5LmdpdGh1Yi5jb20&tok=MjcjamVhbnRlY2huaWNhbDE5OTJAZ21haWwuY29tZjY4ODA1YmNjMTg0ZDNjYjEzZDgzOTJkMjQ2OGM4M2IxOTdiZGM1MA&ctz=America%2FNew_York&hl=en&es=0
Your attendance is optional.

~~//~~
Invitation from Google Calendar: https://calendar.google.com/calendar/

You are receiving this email because you are an attendee on the event. To  
stop receiving future updates for this event, decline this event.

Forwarding this invitation could allow any recipient to send a response to  
the organizer, be added to the guest list, invite others regardless of  
their own invitation status, or modify your RSVP.

Learn more https://support.google.com/calendar/answer/37135#forwarding

**Pull request merged**
